swagger: '2.0'
info:
  description: |
    This is the backend for the TYFW: Track Your Friend's Wallets app for CPEN 321 
  version: 1.0.0
  title: TYFW
  contact:
    email: dryden.wiebe@gmail.com
# host: petstore.swagger.io
# basePath: /v2
tags:
- name: user
  description: The user of this app
# schemes:
# - http
paths:
  /user/authenticate:
    get:
      tags:
      - user
      summary: Authenticate user with Google sign in 
      operationId: authenticate
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: userAuthenticate
        required: true
        schema:
          $ref: '#/definitions/UserAuthenticate'
      responses:
        default:
          description: Successful operation
        400:
          description: Authentication failed
  /user/register:
    post:
      tags:
      - user
      summary: Register an unregistered user
      operationId: register
      produces:
      - application/json
      - application/xml
      parameters:
      - name: register
        in: body
        required: true
        schema:
          $ref: '#/definitions/RegisterUser'
      responses:
        200:
          description: successful operation
        400:
          description: Username already used
        401:
          description: Failure
  /user/getleaderboard:
    get:
      tags:
      - user
      summary: Get the leaderboard to display to a user
      operationId: getLeaderboard
      produces:
      - application/json
      - application/xml
      parameters:
      - name: getLeaderboard
        in: body
        required: true
        schema:
          $ref: '#/definitions/GetLeaderboard'
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/LeaderboardRow'
        400:
          description: Username already used
        401:
          description: Failure
  /user/display:
    get:
      tags:
      - user
      summary: Displays the wallet of the current user
      operationId: display
      produces:
      - application/json
      - application/xml
      parameters:
      - name: display
        in: body
        required: true
        schema:
          $ref: '#/definitions/Display'
      responses:
        200:
          description: successful operation
          schema:
              $ref: '#/definitions/DisplayReturn'
        401:
          description: Failure
  /user/displayotheruserbyusername:
    get:
      tags:
      - user
      summary: Displays the wallet of another user by username
      operationId: displayotheruserbyusername
      produces:
      - application/json
      - application/xml
      parameters:
      - name: displayotheruserbyusername
        in: body
        required: true
        schema:
          $ref: '#/definitions/DisplayOtherUserbyUsername'
      responses:
        200:
          description: successful operation
          schema:
              $ref: '#/definitions/DisplayReturn'
        401:
          description: Failure
  /user/displayotheruserbyaddress:
    get:
      tags:
      - user
      summary: Displays the wallet of another user by wallet address
      operationId: displayotheruserbyaddress
      produces:
      - application/json
      - application/xml
      parameters:
      - name: displayotheruserbyaddress
        in: body
        required: true
        schema:
          $ref: '#/definitions/DisplayOtherUserbyAddress'
      responses:
        200:
          description: successful operation
          schema:
              $ref: '#/definitions/DisplayReturn'
        401:
          description: Failure
  /user/changename:
    get:
      tags:
      - user
      summary: Changes the name of the user
      operationId: changename
      produces:
      - application/json
      - application/xml
      parameters:
      - name: changename
        in: body
        required: true
        schema:
          $ref: '#/definitions/ChangeName'
      responses:
        200:
          description: successful operation
        401:
          description: Failure
  /user/search:
    get:
      tags:
      - user
      summary: Search by username/wallet address
      operationId: search
      produces:
      - application/json
      - application/xml
      parameters:
      - name: search
        in: body
        required: true
        schema:
          $ref: '#/definitions/Search'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/SearchResult'
        401:
          description: Failure
  /user/addbyusername:
    get:
      tags:
      - user
      summary: Add friend by username
      operationId: addbyusername
      produces:
      - application/json
      - application/xml
      parameters:
      - name: addbyusername
        in: body
        required: true
        schema:
          $ref: '#/definitions/AddByUsername'
      responses:
        200:
          description: successful operation
        401:
          description: Failure
  /user/addbywalletaddress:
    get:
      tags:
      - user
      summary: Add friend by wallet address
      operationId: addbywalletaddress
      produces:
      - application/json
      - application/xml
      parameters:
      - name: add by wallet address
        in: body
        required: true
        schema:
          $ref: '#/definitions/AddByWalletAddress'
      responses:
        200:
          description: successful operation
        401:
          description: Failure
definitions:
  UserAuthenticate:
    type: object
    properties:
      email:
        type: string
      googleIdToken:
        type: string
  RegisterUser:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      walletAddress:
        type: string
      googleIdToken:
        type: string
  GetLeaderboard:
    type: object
    properties:
      email:
        type: string
      googleIdToken:
        type: string
  LeaderboardRow:
    type: object
    properties:
      user:
        type: string
      value:
        type: number
  Display:
    type: object
    properties:
      email:
        type: string
      googleIdToken:
        type: string
      numPoints:
        type: integer
  DisplayReturn:
    type: object
    properties:
      startTime:
        type: integer
      endTime:
        type: integer
      numPoints:
          type: string
          enum: [hour, day, month]
      values:
        type: array
        items:
          type: number
  DisplayOtherUserbyUsername:
    type: object
    properties:
      email:
        type: string
      googleIdToken:
        type: string
      otherUsername:
        type: string
      numPoints:
        type: integer
  DisplayOtherUserbyAddress:
    type: object
    properties:
      email:
        type: string
      googleIdToken:
        type: string
      otherUsername:
        type: string
      numPoints:
        type: integer
  ChangeName:
    type: object
    properties:
      nameIdentifier:
        type: string
        enum: [first, last]
      googleIdToken:
        type: string
      newName:
        type: string
  Search:
    type: object
    properties:
      query:
        type: string
      googleIdToken:
        type: string
  SearchResult:
    type: object
    properties:
      query:
        type: string
      googleIdToken:
        type: string
  AddByUsername:
    type: object
    properties:
      friendUsername:
        type: string
      googleIdToken:
        type: string
  AddByWalletAddress:
    type: object
    properties:
      friendWalletAddress:
        type: string
      googleIdToken:
        type: string
host: virtserver.swaggerhub.com
basePath: /drydenwiebe/tyfw/1.0.0
schemes:
 - https
 - http
